main: net.trivernis.superutils.SuperUtils
name: SuperUtils
version: '1.0 SNAPSHOT'
description: Utility commands plugin.
author: Trivernis
website: trivernis.net
commands:
  'superutils reload':
    description: reloads the config of the plugin
    permission: superutils.reload
    permission-message: You do not have permission to reload the configuration!
    usage: /reload
  c:
    description: spectator night vision
    permission: superutils.c
    permission-message: You do not have permission!
    usage: /c
  h:
    description: teleport to default home
    permission: superutils.h
    permission-message: You do not have permission!
    usage: /h [home]
  wp:
    description: warp to essentials warp point
    permission: superutils.wp
    permission-message: You do not have permission!
    usage: /wp {warp}
permissions:
  superutils.reload:
    description: Allows reload command
    default: op
  superutils.c:
    description: Allows c command
    default: op
  superutils.h:
    description: Allow h command
    default: op
  superutils.wp:
    description: Allow wp command
    default: op
  superutils.*:
    description: Wildcard permission
    default: op
    children:
      superutils.c: true